#!/bin/sh

bspc monitor ^1 -d "1 $PANEL_ICON_WORKSPACE1" "2 $PANEL_ICON_WORKSPACE2" "3 $PANEL_ICON_WORKSPACE3" "4 $PANEL_ICON_WORKSPACE4" "5 $PANEL_ICON_WORKSPACE5"
bspc monitor ^2 -d "6 $PANEL_ICON_WORKSPACE6" "7 $PANEL_ICON_WORKSPACE7" "8 $PANEL_ICON_WORKSPACE8" "9 $PANEL_ICON_WORKSPACE9" "10 $PANEL_ICON_WORKSPACE0"

bspc config border_width 2
bspc config window_gap 15
#bspc config top_padding 18
#bspc config bottom_padding 18
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config single_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer false
bspc config click_to_focus true

bspc config normal_border_color $BSPWM_NORMAL_BORDER_COLOR
bspc config active_border_color $BSPWM_ACTIVE_BORDER_COLOR
bspc config focused_border_color $BSPWM_FOCUSED_BORDER_COLOR
bspc config presel_feedback_color $BSPWM_PRESEL_FEEDBACK_COLOR

bspc rule -a Screenkey manage=off
bspc rule -a URxvt:scratchterm sticky=on state=floating
bspc rule -a Code desktop='^3'
bspc rule -a TelegramDesktop desktop='^10'
bspc rule -a Brave-browser desktop='^1'
bspc rule -a qpdfview desktop='^9'

panel &
~/.i3/run.sh
xdo lower $(xdotool search --class dzen)
xdo lower $(xdotool search --class bar)

sxhkd &
nvidia-settings --assign CurrentMetaMode="$(xrandr | sed -nr '/(\S+) connected (primary )?[0-9]+x[0-9]+(\+\S+).*/{ s//\1: nvidia-auto-select \3 { ForceFullCompositionPipeline = On }, /; H }; ${ g; s/\n//g; s/, $//; p }')" &
setxkbmap -option grp:rwin_toggle -layout us,de -variant ,qwerty -option compose:ralt &
xsetroot -cursor_name left_ptr &
urxvtd -q -o -f &
compton &
nitrogen --restore &
unclutter -idle 3 &
clipmenud &
autocutsel -fork &
autocutsel -s PRIMARY -fork &
xset r rate 260 55 &
xset m 3/2 0 &
xset dpms 0 600 1800 &
