if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

if [ -f ~/.profile ]; then
    . ~/.profile
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
